modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/emmanueltremblay9-stack/immersive_deposit_scanner/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="immersive_deposit_scanner_logo.png"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="journeymap"
type="required"
reason="Immersive Deposit Scanner uses JourneyMap for all map visualization."
versionRange="[1.21.1-6.0.0-beta.85,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="immersiveengineering"
type="required"
reason="Immersive Deposit Scanner reads Immersive Engineering core samples."
versionRange="[12.4.2-194,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="immersivepetroleum"
type="required"
reason="Immersive Deposit Scanner reads Immersive Petroleum reservoir survey data."
versionRange="[4.4.1-37,)"
ordering="AFTER"
side="BOTH"

